spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB}?sslmode=require
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

app:
  jwt:
    private-key: ${RSA_PRIVATE_KEY}
